In [1]:
import os
import anndata as an
import scanpy as sc
import pandas as pd
from scipy import sparse

In [3]:
DATAPATH = '/nfs/turbo/umms-indikar/shared/projects/DGC/data/tabula_sapiens/extract'

In [2]:
def get_all_h5ad_files(directory):
    h5ad_files = []
    for root, _, files in os.walk(directory):
        for file in files:
            if file.endswith(".h5ad"):
                h5ad_files.append(os.path.join(root, file))
    return h5ad_files

In [5]:
scH5ADfiles = get_all_h5ad_files(DATAPATH)

In [12]:
adata = sc.read(os.path.join(DATAPATH, scH5ADfiles[1]))
adata

AnnData object with n_obs × n_vars = 82478 × 58870
    obs: 'organ_tissue', 'method', 'donor', 'anatomical_information', 'n_counts_UMIs', 'n_genes', 'cell_ontology_class', 'free_annotation', 'manually_annotated', 'compartment', 'gender'
    var: 'gene_symbol', 'feature_type', 'ensemblid', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: '_scvi', '_training_mode', 'dendrogram_cell_type_tissue', 'dendrogram_computational_compartment_assignment', 'dendrogram_consensus_prediction', 'dendrogram_tissue_cell_type', 'donor_colors', 'donor_method_colors', 'hvg', 'method_colors', 'neighbors', 'organ_tissue_colors', 'sex_colors', 'tissue_colors', 'umap'
    obsm: 'X_pca', 'X_scvi', 'X_scvi_umap', 'X_umap'
    layers: 'decontXcounts', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [8]:
adata

AnnData object with n_obs × n_vars = 11 × 58870
    obs: 'organ_tissue', 'method', 'donor', 'anatomical_information', 'n_counts_UMIs', 'n_genes', 'cell_ontology_class', 'free_annotation', 'manually_annotated', 'compartment', 'gender'
    var: 'gene_symbol', 'feature_type', 'ensemblid', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: '_scvi', '_training_mode', 'dendrogram_cell_type_tissue', 'dendrogram_computational_compartment_assignment', 'dendrogram_consensus_prediction', 'dendrogram_tissue_cell_type', 'donor_colors', 'donor_method_colors', 'hvg', 'method_colors', 'neighbors', 'organ_tissue_colors', 'sex_colors', 'tissue_colors', 'umap'
    obsm: 'X_pca', 'X_scvi', 'X_scvi_umap', 'X_umap'
    layers: 'decontXcounts', 'raw_counts'
    obsp: 'connectivities', 'distances'

In [13]:
adata.var

,gene_symbol,feature_type,ensemblid,highly_variable,means,dispersions,dispersions_norm,mean,std
DDX11L1,DDX11L1,Gene Expression,ENSG00000223972.5,False,6.398244e-05,0.835044,-0.573947,0.000039,0.005574
WASH7P,WASH7P,Gene Expression,ENSG00000227232.5,False,2.274395e-03,2.442280,0.533203,0.001080,0.031731
MIR6859-1,MIR6859-1,Gene Expression,ENSG00000278267.1,False,6.175251e-05,1.295335,-0.256874,0.000033,0.005634
MIR1302-2HG,MIR1302-2HG,Gene Expression,ENSG00000243485.5,False,1.372886e-04,2.656352,0.680668,0.000048,0.008041
MIR1302-2,MIR1302-2,Gene Expression,ENSG00000284332.1,False,1.000000e-12,NaN,0.000000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...
MT-ND6,MT-ND6,Gene Expression,ENSG00000198695.2,False,9.634841e-01,2.466404,0.154140,0.590065,0.741395
MT-TE,MT-TE,Gene Expression,ENSG00000210194.1,False,1.600667e-01,1.603787,-0.044396,0.083929,0.301820
MT-CYB,MT-CYB,Gene Expression,ENSG00000198727.2,False,4.367693e+00,4.765751,-0.499747,3.874830,1.104192
MT-TT,MT-TT,Gene Expression,ENSG00000210195.2,False,6.573967e-02,0.624316,-0.719108,0.040580,0.186848
MT-TP,MT-TP,Gene Expression,ENSG00000210196.2,True,4.385102e-01,2.705558,1.115482,0.204806,0.501265

In [14]:
adata.X

<82478x58870 sparse matrix of type '<class 'numpy.float32'>'
	with 262020791 stored elements in Compressed Sparse Row format>

In [16]:
adata.var.index

Index(['DDX11L1', 'WASH7P', 'MIR6859-1', 'MIR1302-2HG', 'MIR1302-2', 'FAM138A',
       'OR4G4P', 'OR4G11P', 'OR4F5', 'AL627309.1',
       ...
       'MT-ND4', 'MT-TH', 'MT-TS2', 'MT-TL2', 'MT-ND5', 'MT-ND6', 'MT-TE',
       'MT-CYB', 'MT-TT', 'MT-TP'],
      dtype='object', length=58870)

In [22]:
gene_path = "/scratch/indikar_root/indikar1/shared_data/geneformer/resources/token_mapping.csv"
gene_map = pd.read_csv(gene_path)

var = pd.DataFrame({'gene_id' : adata.var.index})
var = pd.merge(var, gene_map, #[['gene_id', 'gene_name', 'gene_biotype', 'scenic_tf']],
               how='left',
               left_on='gene_id',
               right_on='gene_name',
              )

#var['ensembl_id'] = var['gene_id'].copy()
#var = var.set_index('gene_id')
var #= var.astype(str)

,gene_id_x,gene_id_y,token_id,gene_name,nonzero_median,gene_version,gene_biotype,Chromosome,Start,End,scenic_tf
0,DDX11L1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WASH7P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,MIR6859-1,ENSG00000278267,24532.0,MIR6859-1,2.319329,1.0,miRNA,1,17368.0,17436.0,False
3,MIR1302-2HG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MIR1302-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
58865,MT-ND6,ENSG00000198695,17195.0,MT-ND6,6.947054,2.0,protein_coding,MT,14148.0,14673.0,False
58866,MT-TE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58867,MT-CYB,ENSG00000198727,17208.0,MT-CYB,55.023306,2.0,protein_coding,MT,14746.0,15887.0,False
58868,MT-TT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58869,MT-TP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
gene_map

,gene_id,token_id,gene_name,nonzero_median,gene_version,gene_biotype,Chromosome,Start,End,scenic_tf
0,<pad>,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,<mask>,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,ENSG00000000003,2,TSPAN6,2.001186,15.0,protein_coding,X,100627107.0,100639991.0,False
3,ENSG00000000005,3,TNMD,3.228213,6.0,protein_coding,X,100584935.0,100599885.0,False
4,ENSG00000000419,4,DPM1,2.218874,14.0,protein_coding,20,50934866.0,50959140.0,False
...,...,...,...,...,...,...,...,...,...,...
25421,ENSGR0000197976,25421,NaN,2.229061,NaN,NaN,NaN,NaN,NaN,False
25422,ENSGR0000198223,25422,NaN,1.900695,NaN,NaN,NaN,NaN,NaN,False
25423,ENSGR0000205755,25423,NaN,1.460207,NaN,NaN,NaN,NaN,NaN,False
25424,ENSGR0000214717,25424,NaN,2.085950,NaN,NaN,NaN,NaN,NaN,False
25425,ENSGR0000265658,25425,NaN,2.298263,NaN,NaN,NaN,NaN,NaN,False

In [19]:
gene_map

,gene_id,token_id,gene_name,nonzero_median,gene_version,gene_biotype,Chromosome,Start,End,scenic_tf
0,<pad>,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,<mask>,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,ENSG00000000003,2,TSPAN6,2.001186,15.0,protein_coding,X,100627107.0,100639991.0,False
3,ENSG00000000005,3,TNMD,3.228213,6.0,protein_coding,X,100584935.0,100599885.0,False
4,ENSG00000000419,4,DPM1,2.218874,14.0,protein_coding,20,50934866.0,50959140.0,False
...,...,...,...,...,...,...,...,...,...,...
25421,ENSGR0000197976,25421,NaN,2.229061,NaN,NaN,NaN,NaN,NaN,False
25422,ENSGR0000198223,25422,NaN,1.900695,NaN,NaN,NaN,NaN,NaN,False
25423,ENSGR0000205755,25423,NaN,1.460207,NaN,NaN,NaN,NaN,NaN,False
25424,ENSGR0000214717,25424,NaN,2.085950,NaN,NaN,NaN,NaN,NaN,False
25425,ENSGR0000265658,25425,NaN,2.298263,NaN,NaN,NaN,NaN,NaN,False

In [18]:
var

            gene_name gene_biotype scenic_tf   ensembl_id
gene_id
DDX11L1           nan          nan       nan      DDX11L1
WASH7P            nan          nan       nan       WASH7P
MIR6859-1         nan          nan       nan    MIR6859-1
MIR1302-2HG       nan          nan       nan  MIR1302-2HG
MIR1302-2         nan          nan       nan    MIR1302-2
...               ...          ...       ...          ...
MT-ND6            nan          nan       nan       MT-ND6
MT-TE             nan          nan       nan        MT-TE
MT-CYB            nan          nan       nan       MT-CYB
MT-TT             nan          nan       nan        MT-TT
MT-TP             nan          nan       nan        MT-TP

[58870 rows x 4 columns]

In [ ]:
adata.var = var
adata